### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by top-master** [mhdhejazi/Dynamic#13]
Could not find any mention of license anywhere?
I hope the license is Apache 2.0 (cause does not need me to mention contribution, I think).

**Comment by nekrich** [comment]
Same here.
I hope for [MIT](https://choosealicense.com/licenses/mit/) 😅. But [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/) would be good too.
But any way legally it looks like a [no-permission](https://choosealicense.com/no-permission/) license.

**Comment by mhdhejazi** [comment]
I've added Apache 2.0 license to the repo. Thank you everyone and sorry for the late update.
