### ISSUE TITLE
Does not compile on watchOS 

### ISSUE THREAD

**Issue by LeoNatan** [mhdhejazi/Dynamic#2]
Hello,

Great library!
The project does not compile for watchOS. There are complaints about certain types that did not exist in watchOS 2.0 (the minimum target), and usage of `CATransform3D`, which isn’t exposed on watchOS. 

Thanks

**Comment by mhdhejazi** [comment]
I think it's ok to update the minimum target to watchOS 3.0 and define `asCATransform3D` for iOS and macOS only. I'll do that.

**Comment by LeoNatan** [comment]
Thank you!
