### ISSUE TITLE
Unable to access Dynamic.

### ISSUE THREAD

**Issue by ohmprakash619** [mhdhejazi/Dynamic#21]
<img width="1042" alt="Screenshot 2021-07-21 at 7 25 31 AM" src="https://user-images.githubusercontent.com/3839300/126418366-dac1dc7d-f3cc-4bad-9ad7-3a6fb18c93e2.png">
Unable to build because of this issue. Anyone facing the same problem? or is it me?

**Comment by mhdhejazi** [comment]
Looks like you have another library that has a generic class also named `Dynamic`. In this case, you can use `ObjC` instead of `Dynamic`
```swift
var nsWindow = ObjC.NSApplication.sharedApplication ...
```
