### ISSUE TITLE
NSWindow in macCatalyst.

### ISSUE THREAD

**Issue by TheDudeOne** [mhdhejazi/Dynamic#3]
Hello, Just used your dynamic repo it is amazing i appreciate your work.
But whenever i try to access NSWindow i get error "unexpectedly found nil while unwrapping an optional value". 
Here is my code : 
```
extension UIWindow {
  var nsWindow: NSObject? {
    Dynamic.NSApplication.sharedApplication.delegate.hostWindowForUIWindow(self)
  }
}

func setScreen(){
  let ns = self.window?.nsWindow
  Dynamic(ns!).setFrame(CGRect(250,200,1200,800), display: true)
  let frame = Dynamic(ns!).frame.asCGRect!
  let size = frame.size 
  Dynamic(ns!).setAspectRatio(CGSize(1.0, size.height/size.width)) 
} 
```

**Comment by mhdhejazi** [comment]
Please make sure `self.window` isn't `nil`.
Also, force unwrapping an optional is risky if you're not 100% sure it won't be `nil`. It's better to use `if let` instead.

**Comment by polymerchm** [comment]
Need to be sure that the window is fully "instantiated" and visible.

**Comment by TheDudeOne** [comment]
it worked.Thanks so much
