### ISSUE TITLE
How to check if the window is in full screen mode or not ?

### ISSUE THREAD

**Issue by TheDudeOne** [mhdhejazi/Dynamic#6]
I want to check whether the window is in full screen or not in mac Catalyst. How can I do that using dynamic?

**Comment by mhdhejazi** [comment]
Is this (#5) what you're asking for?

**Comment by gabors** [comment]
Hi @mhdhejazi 
That approach while working great on Catalina no longer works in Big Sir.
I'll add the debugger output details

**Comment by mhdhejazi** [comment]
Some API has been changed on macOS 11. Check if this solution (https://github.com/mhdhejazi/Dynamic/issues/7#issuecomment-729584944) makes things work again.

**Comment by polymerchm** [comment]
Where is the documentation on these API changes.

Sent from Xfinity Connect App

------ Original Message ------

**Comment by mhdhejazi** [comment]
`hostWindowForUIWindow()` is a private API. So, there is no documentation for it.

**Comment by polymerchm** [comment]
Got it. Need to learn class-dump. :-)

Sent from Xfinity Connect App

------ Original Message ------

**Comment by waverun** [comment]
Consider the following to detect full screen (on macCatalyst mode):

#if targetEnvironment(macCatalyst)
extension UIScreen {
    static var isFullScreen: Bool {
        let options = CGWindowListOption(arrayLiteral: CGWindowListOption.optionAll)
        let cgWindowListInfo = CGWindowListCopyWindowInfo(options, CGWindowID(0))
        let cgWindowListInfo2 = cgWindowListInfo as NSArray? as? [[String: AnyObject]]

        for windowDict in cgWindowListInfo2 ?? [] {
            let windowParams = "\(windowDict)"
            if windowParams.contains("Y = \"-") && windowParams.contains(", \"kCGWindowIsOnscreen\": 1")
            {
            //                print("windowDict: \(windowDict)")
            return true
            }
        }
        return false
    }
}
#endif
