### ISSUE TITLE
WARNING: Trying to access an unrecognized member: NSWorkspace.shared

### ISSUE THREAD

**Issue by cruinh** [mhdhejazi/Dynamic#8]
I have your package installed and imported into my project, and I'm trying to use it to open a folder in Finder from a new SwiftUI app.  I tried hooking it up to a menu item like so:

![Screen Shot 2021-01-12 at 9 45 32 AM](https://user-images.githubusercontent.com/96700/104337360-06861480-54bb-11eb-8c8b-8bab5382a617.png)

The menu and button appears just fine, but when I click it this appears in the console:

`WARNING: Trying to access an unrecognized member: NSWorkspace.shared`

This is on macOS 11.1 with Xcode 12.3

**Comment by mhdhejazi** [comment]
The correct name for ObjC is [`sharedWorkspace`](https://developer.apple.com/documentation/appkit/nsworkspace/1530344-sharedworkspace?language=objc), so that's what you should use here. Make sure to always check the method signature for ObjC.

**Comment by cruinh** [comment]
Oh that did the trick.  Thank you! 

I did also have to adjust the arguments I passed to actually get it to open, but this worked.
`Dynamic.NSWorkspace.sharedWorkspace.selectFile("/Users/", inFileViewerRootedAtPath: "/Users/")`

**Comment by mhdhejazi** [comment]
Glad it works!
